package com.clm.platform.security;

public enum Permission {

	TENANT_READ,
	TENANT_MANAGE,
	ORGANIZATION_READ,
	ORGANIZATION_MANAGE,
	ROLE_READ,
	ROLE_MANAGE,
	CERTIFICATE_READ,
	CERTIFICATE_IMPORT,
	CERTIFICATE_MANAGE,
	SERVICE_ACCOUNT_READ,
	SERVICE_ACCOUNT_MANAGE,
	AUDIT_READ,
	SENSITIVE_ACTION_EXECUTE,
	TASK_READ,
	TASK_MANAGE
}
